INSERT INTO `pes_option` ( `option_name`, `name`, `value`, `option_range`) VALUES
('siteLogo', '网站LOGO', '/Theme/assets/i/logo.png', 'system'),
('siteTitle', '网站名称', 'PESCMS Ticket', 'system'),
('pescmsIntroduce', '页脚内容', '<div class="am-u-sm-12 am-u-lg-11 am-u-sm-centered">\n    <div class="am-g">\n        <div class="am-u-sm-12 am-u-lg-3">\n            <h4>关于PESCMS</h4>\n            <p>PESCMS旗下有TEAM团队任务管理系统，Ticket客服工单系统，DOC文档管理系统以及基于浏览器开发的基金定投助手。</p>\n        </div>\n        <div class="am-u-sm-12 am-u-lg-3">\n            <h4>产品列表</h4>\n            <ul>\n                <li><a href="https://www.pescms.com/download/2.html">PESCMS TEAM 团队任务管理系统</a></li>\n                <li><a href="https://www.pescms.com/download/3.html">PESCMS DOC 文档管理系统</a></li>\n                <li><a href="https://www.pescms.com/download/5.html">PESCMS TICKET 客服工单系统</a></li>\n                <li><a href="https://www.pescms.com/download/4.html">PESCMS LOGIN 网站登录管理</a></li>\n                <li><a href="https://www.pescms.com/download/6.html">基金定投助手</a></li>\n            </ul>\n        </div>\n        <div class="am-u-sm-12 am-u-lg-3 am-u-end">\n            <h4>产品服务</h4>\n            <ul>\n                <li><a href="https://www.pescms.com/Page/Authorization.html">商业授权</a></li>\n                <li><a href="https://www.pescms.com/Authorize-Verify">授权查询</a></li>\n                <li><a href="https://www.pescms.com/service.html">有偿服务</a></li>\n                <li><a href="https://www.pescms.com/Page/ad.html">广告投放</a></li>\n                <li><a href="https://www.pescms.com/Page/donate.html">赞助捐赠</a></li>\n            </ul>\n        </div>\n    </div>\n</div>', 'system'),
('siteContact', '网站联系方式', '<span class="am-margin-right-xs"><i class="am-icon-qq"></i> <a href="https://wpa.qq.com/msgrd?v=3&uin=201418824&menu=yes" target="_blank">201418824</a></span>\n<span class="am-margin-right-xs"><i class="am-icon-weixin"></i> <a href="javascript:;" data-am-popover="{content: ''<img src=\\''https://www.pescms.com/Theme/assets/i/IMG_2866.JPG\\'' width=300>'', trigger: ''hover focus''}" >PESCMS</a></span>\n<span class="am-margin-right-xs"><i class="am-icon-thumbs-o-up"></i> <a href="javascript:;" data-am-popover="{content: ''<img src=\\''https://www.pescms.com/Theme/assets/i/zan.png\\'' width=300>'', trigger: ''hover focus''}" >打赏支持</a></span>', 'system');


INSERT INTO `pes_option` (`option_name`, `name`, `value`, `option_range`) VALUES
('authorize', '授权码', '', '');
